"""empty message

Revision ID: 0b2e83e50d78
Revises: ee039a1d6bc0
Create Date: 2021-06-22 12:56:11.444772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2e83e50d78'
down_revision = 'ee039a1d6bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brandname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brandname')
    # ### end Alembic commands ###
