"""empty message

Revision ID: 796e0400a3fc
Revises: 0b2e83e50d78
Create Date: 2021-06-22 13:18:01.790060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796e0400a3fc'
down_revision = '0b2e83e50d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('specialisation', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
