"""empty message

Revision ID: 7a223bacfc69
Revises: cda884d95821
Create Date: 2021-06-22 11:28:42.970675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a223bacfc69'
down_revision = 'cda884d95821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
